[WIP] Add encryption process
MoarCatz/chat-server pull request #4
Opened 2016-11-03 20:10 UTC by alexbagirov

Refs #3

2016-11-03 20:18 UTC, Leva7 commented on installer.py
> +                                              password text,
What's up with indentation here?

2016-11-03 20:20 UTC, alexbagirov commented on installer.py
> +                                              password text,
Thanks!

It looks better now :+1:

2016-11-03 21:32 UTC, illright approved these changes

2016-11-04 16:03 UTC, alexbagirov commented
What we need here is to write some tests :smile:

2016-11-04 17:21 UTC, illright approved these changes

2016-11-05 10:56 UTC, illright requested changes
Remove the `templates` folder

2016-11-05 12:42 UTC, illright approved these changes

2016-11-10 18:52 UTC, closed without merging