Add removing old sessions functionality and cron script
MoarCatz/chat-server pull request #9
Opened 2016-11-12 20:10 UTC by alexbagirov

refs #7

2016-11-12 20:26 UTC, illright requested changes

2016-11-12 20:26 UTC, Leva7 commented on session_cleaner.py
> +             WHERE last_active < %s''', (str(stamp)))
`str(stamp)` is a string representation of a `datetime` object, not the timestamp. Also, you forgot a comma to make the parentheses form a tuple

2016-11-12 20:26 UTC, Leva7 commented on processors.py
> +        таблицы sessions"""
Why on Earth is following general conventions that hard?

2016-11-12 20:28 UTC, alexbagirov commented on processors.py
> +        таблицы sessions"""
If you want to say something, just say it and not the shit you've just said.

2016-11-12 20:29 UTC, alexbagirov commented on session_cleaner.py
> +             WHERE last_active < %s''', (str(stamp)))
So yes, we have `em stored as text and it seems to be fine.

2016-11-13 06:04 UTC, Leva7 commented on processors.py
> +        таблицы sessions"""
Well, it's the third time my comment disappears, so fine, I'll say it again. A `.timestamp()` method is to be called on an `datetime` object with no arguments, not an a class. We don't call `str.upper('string')`, the same thing here

2016-11-13 06:06 UTC, illright commented on session_cleaner.py
> +             WHERE last_active < %s''', (str(stamp), ))
You want `str(stamp.timestamp())` here. Don't confuse yourself with misleading variable names. Call it `date` or something

2016-11-13 15:49 UTC, alexbagirov commented
Ready for review :tada:

2016-11-15 18:39 UTC, illright approved these changes

2016-11-15 18:43 UTC, merged